import { SyntaxStyle } from "@opentui/core"

// Catppuccin Macchiato palette; the capture names follow the tree-sitter
// highlight convention used by @opentui/core grammars (and Neovim).
const palette = {
  rosewater: "#f4dbd6", flamingo: "#f0c6c6", pink: "#f5bde6", mauve: "#c6a0f6",
  red: "#ed8796", maroon: "#ee99a0", peach: "#f5a97f", yellow: "#eed49f",
  green: "#a6da95", teal: "#8bd5ca", sky: "#91d7e3", sapphire: "#7dc4e4",
  blue: "#8aadf4", lavender: "#b7bdf8", text: "#cad3f5", subtext: "#a5adcb",
  overlay: "#8087a2",
}

export function createSyntaxStyle(): SyntaxStyle {
  return SyntaxStyle.fromStyles({
    default: { fg: palette.text },
    comment: { fg: palette.overlay, italic: true },
    "comment.documentation": { fg: palette.overlay, italic: true },
    string: { fg: palette.green },
    "string.escape": { fg: palette.rosewater },
    "string.special": { fg: palette.rosewater },
    "string.special.key": { fg: palette.rosewater },
    escape: { fg: palette.rosewater },
    character: { fg: palette.green },
    "character.special": { fg: palette.rosewater },
    constant: { fg: palette.peach },
    "constant.builtin": { fg: palette.peach },
    "constant.macro": { fg: palette.mauve },
    number: { fg: palette.peach },
    boolean: { fg: palette.peach },
    float: { fg: palette.peach },
    function: { fg: palette.blue },
    "function.builtin": { fg: palette.sapphire },
    "function.call": { fg: palette.blue },
    "function.macro": { fg: palette.mauve },
    "function.method": { fg: palette.blue },
    "function.method.call": { fg: palette.blue },
    method: { fg: palette.blue },
    "method.call": { fg: palette.blue },
    constructor: { fg: palette.yellow },
    keyword: { fg: palette.mauve, italic: true },
    "keyword.function": { fg: palette.mauve },
    "keyword.operator": { fg: palette.mauve },
    "keyword.return": { fg: palette.mauve },
    conditional: { fg: palette.mauve },
    "conditional.ternary": { fg: palette.mauve },
    repeat: { fg: palette.mauve },
    define: { fg: palette.mauve },
    macro: { fg: palette.mauve },
    include: { fg: palette.pink },
    label: { fg: palette.lavender },
    exception: { fg: palette.pink },
    debug: { fg: palette.pink },
    operator: { fg: palette.sky },
    punctuation: { fg: palette.subtext },
    delimiter: { fg: palette.overlay },
    "punctuation.bracket": { fg: palette.overlay },
    "punctuation.delimiter": { fg: palette.overlay },
    "punctuation.special": { fg: palette.rosewater },
    type: { fg: palette.teal },
    "type.builtin": { fg: palette.teal },
    "type.definition": { fg: palette.teal },
    "type.qualifier": { fg: palette.mauve },
    typedef: { fg: palette.teal },
    struct: { fg: palette.teal },
    enum: { fg: palette.teal },
    interface: { fg: palette.teal },
    variable: { fg: palette.text },
    "variable.builtin": { fg: palette.red, italic: true },
    "variable.parameter": { fg: palette.maroon },
    "variable.parameter.reference": { fg: palette.maroon },
    "variable.member": { fg: palette.rosewater },
    "variable.bash": { fg: palette.mauve },
    property: { fg: palette.rosewater },
    field: { fg: palette.rosewater },
    parameter: { fg: palette.maroon },
    "parameter.reference": { fg: palette.maroon },
    namespace: { fg: palette.yellow },
    attribute: { fg: palette.yellow },
    "attribute.builtin": { fg: palette.yellow },
    tag: { fg: palette.blue },
    "tag.builtin": { fg: palette.blue },
    "tag.delimiter": { fg: palette.overlay },
    "tag.attribute": { fg: palette.yellow },
    embedded: { fg: palette.rosewater },
    title: { fg: palette.text, bold: true },
    underline: { underline: true },
    "diff.plus": { fg: palette.green },
    "diff.minus": { fg: palette.red },
    "diff.delta": { fg: palette.blue },
    "markup.heading": { fg: palette.text, bold: true },
    "markup.strong": { fg: palette.text, bold: true },
    "markup.italic": { fg: palette.text, italic: true },
    "markup.list": { fg: palette.blue },
    "markup.quote": { fg: palette.overlay, italic: true },
    "markup.raw": { fg: palette.green },
    "markup.link": { fg: palette.blue, underline: true },
    paste: { fg: "#e9b872", bold: true },
  })
}
